a=int(input("inserisci un numero: "))
print("questo è il doppio", a*2)
print("questo è il triplo: ", a*3)
b=input("ora che hai visto i suoi primi 2 multipli è ora di farmi sapere il tuo nome: ")
print(b, "è un bellissimo nome:)")